In [1]:
#EXP NO: 2

In [2]:
#Aim: to perform operation of exploratory data analysis

In [4]:
#Name:Arushi Rajendra Jadhav
#Roll:26
#sec:C
#subject:DSS

import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\USER'

In [9]:
os.chdir("C:\\Users\\USER\\OneDrive\\Desktop")

In [10]:
data = pd.read_csv('heart.csv')

In [11]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [12]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [13]:
data.shape

(303, 14)